################################################################################
#                           DE10_DEMO LCD specifics                            #
################################################################################
TARGET = DEMO_LCD
OBJS = LCD_Driver terasic_lib LCD_Graphic main

include ../common.mk
