# TCL File Generated by Component Editor 17.0
# Fri Jan 05 10:55:10 CET 2018
# DO NOT MODIFY


# 
# manager "manager" v1.0
# Badiss Djafar 2018.01.05.10:55:10
# Bitcoin Mining Manager
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module manager
# 
set_module_property DESCRIPTION "Bitcoin Mining Manager"
set_module_property NAME manager
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP bitcoin
set_module_property AUTHOR "Badiss Djafar"
set_module_property DISPLAY_NAME manager
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL manager
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file manager.vhd VHDL PATH manager.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter MAX_QUEUE_DEPTH NATURAL 8 ""
set_parameter_property MAX_QUEUE_DEPTH DEFAULT_VALUE 8
set_parameter_property MAX_QUEUE_DEPTH DISPLAY_NAME MAX_QUEUE_DEPTH
set_parameter_property MAX_QUEUE_DEPTH WIDTH ""
set_parameter_property MAX_QUEUE_DEPTH TYPE NATURAL
set_parameter_property MAX_QUEUE_DEPTH UNITS None
set_parameter_property MAX_QUEUE_DEPTH ALLOWED_RANGES 0:2147483647
set_parameter_property MAX_QUEUE_DEPTH DESCRIPTION ""
set_parameter_property MAX_QUEUE_DEPTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock_sink
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave slWaitrequest waitrequest Output 1
add_interface_port avalon_slave slWriteIn write Input 1
add_interface_port avalon_slave slvByteEnableIn byteenable Input 16
add_interface_port avalon_slave slvAddrIn address Input 4
add_interface_port avalon_slave slvWritedataIn writedata Input 128
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink slResetInput reset Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink slClkInput clk Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock_sink
set_interface_property avalon_streaming_source associatedReset reset_sink
set_interface_property avalon_streaming_source dataBitsPerSymbol 512
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source slvStreamDataOut data Output 512
add_interface_port avalon_streaming_source slValidOutput valid Output 1
add_interface_port avalon_streaming_source slvChanOuput channel Output 4
add_interface_port avalon_streaming_source slReadyInput ready Input 1

